config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :providers, :as => "users", :only => [:show, :index] do
    collection do
      get :search
    end
    resources :contributions, :only => [:new, :create, :show, :index] do
      collection do
        get :add_product
      end
    end
  end

  resources :profiles, :only =>[:edit, :update, :show]
  root to: "home#index"

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :profile
  geocoded_by :geocode_string
  before_update :geocode, if: lambda { |address| address.changed? }

  def geocode_string
    "#{door_number} #{street}, #{postcode}, #{city}, #{country}"
  end

  def self.find_addresses_by_distance(addresses, referenced_address, distance)
    addresses = addresses.near([referenced_address.latitude, referenced_address.longitude], distance)
  end
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :charity
  belongs_to :contribution
  after_save :notify_provider

  private
  def notify_provider
    @charity = self.charity
    @provider = self.contribution.user
    UserNotification.notification(@provider, @charity).deliver_now
  end
end

app/models/charity.rb
class Charity < User
end

app/models/contribution.rb
class Contribution < ActiveRecord::Base
  has_one :booking
  belongs_to :user

  has_many :products, inverse_of: :contribution
  accepts_nested_attributes_for :products, allow_destroy: :true, reject_if: proc { |attributes| attributes[:product_name].blank? }

  validates :collection_date, :collection_time, presence: :true
  validate :must_have_one_product, :collection_date_validity

  def self.providers_as_json(providers)
    providers_json = []

    providers.each do |provider|
      providers_json << provider.as_json
    end
    providers_json
  end

  def must_have_one_product
    if products.empty?
      errors.add(:products, "must have at least one product") if products.empty?
      self.products << Product.new
    end
  end

  def collection_date_validity
    errors.add(:collection_date, "cannot be in the past") if collection_date < Date.today
  end

  def self.list_contributions(providers)
    contributions = []
    providers.each do |provider|
      contributions << provider.contributions[0]
    end
    contributions
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :contribution, inverse_of: :products
  validates_presence_of :contribution
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_one :address
  belongs_to :user
  accepts_nested_attributes_for :address, :user

  after_create :create_address

  mount_uploader :avatar, AvatarUploader

  private
  def create_address
    Address.create!(profile: self)
  end
end

app/models/provider.rb
class Provider < User
  has_many :contributions, foreign_key: 'user_id'

  def self.find_providers(providers_with_contributions, addresses)
    providers = []
    providers_with_contributions.each do |provider|
      addresses.each do |address|
        if provider == address.profile.user
          providers << address.profile.user
          break
        end
      end
    end
    providers
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :organization_name, presence: true
  has_one :profile
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :create_profile


  def as_json
    address = self.profile.address
    user_as_json = {
      "organizationName" => self.organization_name,
      "email" => self.email,
      "address" => address.geocode_string,
      "latitude" => address.latitude,
      "longitude" => address.longitude
    }
    user_as_json
  end

  private
  def create_profile
    Profile.create!(user: self)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:organization_name, :email, :password, :password_confirmation, :type)}
  end

  def after_sign_in_path_for(resource)
    profile_path(resource.profile)
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :load_contribution, :only => [:show]
  before_action :authenticate_user!
  append_before_action :restrict_access, :only => [:new]

  def new
    @contribution = Contribution.new
    @contribution.products << Product.new
  end

  def create
    @contribution = Contribution.new(user_id: params[:user_id])
    @contribution.assign_attributes(contribution_params)
    begin
      @contribution.save!
      flash[:notice] = "A contribution has been created"
      redirect_to user_contribution_path(@contribution, user_id: params[:user_id])
    rescue
      render :new
    end
  end

  def index
    @contributions = Contribution.joins(:user).where("users.id =?", params[:user_id])
  end

  def add_product
    Product.new
  end

  private
  def contribution_params
    params.require(:contribution).permit(:collection_date, :collection_time, :products_attributes => [:quantity, :product_name, :perishable])
  end

  def load_contribution
    @contribution = Contribution.find(params[:id])
  end

  def restrict_access
    render :status => 403, :text => "Forbidden User Access" unless current_user.id == params[:user_id].to_i && current_user.type == "Provider"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :load_profile
  append_before_action :authenticate_user!
  append_before_action :restrict_access, :only => [:edit]

  def update
    begin
      @profile.update!(profile_params)
      redirect_to profile_path(@profile)
    rescue
      render :edit
    end
  end

  def show
    uploader = @profile.avatar
    uploader.retrieve_from_store!(@profile.avatar_identifier)
  end

  private
  def profile_params
    params.require(:profile).permit(:avatar, :user_attributes => [:id, :organization_name, :email], :address_attributes => [:id, :door_number, :street, :city, :country, :postcode])
  end

  def load_profile
    @profile = Profile.find(params[:id])
  end

  def restrict_access
    render :status => 403, :text => "Forbidden profile" unless current_user == @profile.user
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_filter :authenticate_user!
  def index
    @providers = Provider.joins(:contributions).uniq
    @charity_as_json = current_user.as_json
    @providers_as_json = Contribution.providers_as_json(Provider.joins(:contributions).limit(10))
  end

  def search
    @charity_address = current_user.profile.address
    @distance = params[:distance]

    @addresses = Address.joins(:profile => :user).where("users.type = ?", "Provider")
    @addresses = Address.find_addresses_by_distance(@addresses, @charity_address, @distance)
    @eager_load_addresses = @addresses.includes(:profile => :user)

    @providers_with_contributions = Provider.joins(:contributions).uniq

    @providers = Provider.find_providers(@providers_with_contributions, @eager_load_addresses)

    @providers_as_json = Contribution.providers_as_json(@providers)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/contributions/_contribution.html.haml
%li
  %fieldset
    %dl
      %dt
        Collection date and time
      %dd
        = "#{ contribution.collection_date}  #{ contribution.collection_time.to_s(:time)} "
      %dt
        Products
      %dd
        - contribution.products.each do |p|
          %ul#products-list
            %li.product
              %span
                = "Quantity #{p.quantity}"
              %span
                = "Product Name: #{p.product_name}"
              %span
                = "Perishable: #{p.perishable}"

app/views/contributions/add_product.js.erb
console.log(i);
$("#products-list").append(
"<li class='product'>" +
  "<label for='contribution_products_attributes_" + i + "_quantity'>Quantity</label>" +
  "<input type='text' name='contribution[products_attributes][" + i + "][quantity]' id='contribution_products_attributes_" + i + "_quantity'>" +
  "<label for='contribution_products_attributes_" + i + "_product_name'>Product name</label>" +
  "<input type='text' name='contribution[products_attributes][" + i + "][product_name]' id='contribution_products_attributes_" + i + "_product_name'>" +
  "<label for='contribution_products_attributes_" + i + "_perishable'>Perishable</label>" +
  "<input name='contribution[products_attributes][" + i + "][perishable]' type='hidden' value='0'><input type='checkbox' value='1' name='contribution[products_attributes][" + i + "][perishable]' id='contribution_products_attributes_" + i + "_perishable'>" +
"</li>"
);
i++;

app/views/contributions/index.html.haml
#results.col-2-3.push-col-1-6
  %h1 List of all contributions available
  %ul
    - @contributions.each do |contribution|
      = render contribution

app/views/contributions/new.html.haml
.col-3-4.push-col-1-8
  %h1 Your contribution helps
  %h2 Products


  - unless @contribution.errors.messages.empty?
    %p Contribution cannot be created because the following fields are required
    - @contribution.errors.messages.each do |key, value|
      %ul#errors
        %li.field-required
          = "#{key.to_s.capitalize!.gsub('_', " ")}: #{value[0]} "

  = form_for ([:user, @contribution]) do |f|
    %fieldset
      = f.fields_for :products do |p|
        %ul#products-list
          %li{class:"product"}
            = p.label :quantity
            = p.text_field :quantity

            = p.label :product_name
            = p.text_field :product_name

            = p.label :perishable
            = p.check_box :perishable
      = link_to "Add product", add_product_user_contributions_path, :remote => true
      .collection-date
        = f.label :collection_date
        = f.date_select(:collection_date, order: [:day, :month, :year], prompt: {day: 'Choose day', month: 'Choose month', year: 'Choose year'}, start_year: Date.today.year, end_year: Date.today.year + 1)
      .collection-time
        = f.label :collection_time
        = f.time_select(:collection_time, {prompt: {hour: 'Choose hour', minute: 'Choose minute'}, minute_step: 15, ignore_date: true})

    = f.submit "Add contribution"

  :javascript
    var i = $(".product").length

app/views/contributions/show.html.haml
%h1
  Details of your contribution
%fieldset
  %table
    %tbody
      %tr
        %td Quantity
        %td Product Name
        %td Perishable

      - @contribution.products.each do |p|
        %tr
          %td
            = "#{p.quantity}"
          %td
            = "#{p.product_name}"
          %td
            = "#{p.perishable}"
= link_to "Back to profile", profile_path(@contribution.user.profile)

app/views/home/index.html.haml
%h1
  Welcome to Sustainable use of food waste

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Usingfoodwasteapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="grid grid-pad">
    <header>
      <a href="<%= root_path %>">
        <i id="logo"><span id="site-title">Sustainable Use of Food Waste</span></i>
      </a>
      <nav>
        <ul id="desktop-menu">
          <% if current_user %>
            <li><%= link_to 'My Profile', profile_path(current_user.profile) %></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: 'DELETE' %></li>
            <% if current_user.type == "Provider" %>
              <li><%= link_to "Add contribution", new_user_contribution_path(:user_id => current_user.id) %></li>
              <li><%= link_to "Your contributions", user_contributions_path(:user_id => current_user.id) %></li>
            <% else %>
              <li><%= link_to "Providers available", users_path %></li>
            <% end %>
          <% else %>
            <li><%= link_to 'Register', new_user_registration_path %></li>
            <li><%= link_to 'Log In', new_user_session_path %></li>
          <% end %>
        </ul>
      </nav>

      <%= image_tag "hamburger.png", id: "hamburger" %>
      <div id="mobile-navigation">
        <ul>
          <% if current_user %>
            <li><%= link_to 'My Profile', profile_path(current_user.profile) %></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: 'DELETE' %></li>
            <% if current_user.type == "Provider" %>
              <li><%= link_to "Add contribution", new_user_contribution_path(:user_id => current_user.id) %></li>
              <li><%= link_to "Your contributions", user_contributions_path(:user_id => current_user.id) %></li>
            <% else %>
              <li><%= link_to "Providers available", users_path %></li>
            <% end %>
          <% else %>
            <li><%= link_to 'Register', new_user_registration_path %></li>
            <li><%= link_to 'Log In', new_user_session_path %></li>
          <% end %>
        </ul>
      </div>
    </header>
  </div>
  <div class="grid grid-pad">
    <main>
      <div class="grid">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </main>
  </div>
  <div class="grid grid-pad">
    <footer>
      &#169; Sostenible Use of Food Waste
    </footer>
  </div>
</body>
</html>

app/views/profiles/edit.html.haml
.col-2-3.push-col-1-8
  %h1 Edit profile
  - unless @profile.errors.messages.empty?
    %p
      Profile cannot be created because of the following reasons
      %ul#errors
        - @profile.errors.messages.each do |key, value|
          %li.field-required
            = "#{key}: #{value[0]}"

  = form_for @profile do |f|
    %fieldset
      = f.fields_for :user do |u|
        = u.label :organization_name
        = u.text_field :organization_name, value: @profile.user.organization_name
        = u.label :email
        = u.text_field :email, value: @profile.user.email
    %fieldset
      = f.label :address
      = f.fields_for :address do |a|
        = a.label :door_number
        = a.text_field :door_number, value: @profile.address.door_number
        = a.label :street
        = a.text_field :street, value: @profile.address.street
        = a.label :city
        = a.text_field :city, value: @profile.address.city
        = a.label :country
        = a.text_field :country, value: @profile.address.country
        = a.label :postcode
        = a.text_field :postcode, value: @profile.address.postcode

    %fieldset
      = image_tag(@profile.avatar.url) if @profile.avatar?
      = f.label :avatar
      = f.file_field :avatar

    = f.submit "Update"

app/views/profiles/show.html.haml
.col-1-2.push-col-1-8
  %h1 Profile information
  %dl
    %dt
      User type
    %dd
      = @profile.user.type

    %dt
      Organization name
    %dd
      = @profile.user.organization_name

    %dt
      Email
    %dd
      = @profile.user.email

    %dt
      Address
    %dd
    - if @profile.address.nil?
      = link_to "Add address", edit_profile_path(@profile)
    - else
      #address
        %span
          = "Door number: #{ @profile.address.door_number}"
        %span
          = "Street: #{ @profile.address.street}"
        %span
          = "City: #{ @profile.address.city}"
        %span
          = "Country: #{ @profile.address.country}"
        %span
          = "Postcode: #{ @profile.address.postcode}"

.avatar.col-1-2
  %span Avatar
  = image_tag(@profile.avatar.url) if @profile.avatar?
  .nav
  - if current_user == @profile.user
    = link_to "Edit", edit_profile_path(@profile), class: "edit"

app/views/providers/_provider.html.haml
%li
  %fieldset
    %span#provider-title
      = "#{provider.organization_name}"
    %span#distance
      = "Distance: #{ provider.profile.address.distance_from([current_user.profile.address.latitude, current_user.profile.address.longitude]).round(2) } miles"
    %nav
      = link_to "Contributions", user_contributions_path(provider)
      = link_to "Show profile", profile_path(provider)

app/views/providers/index.html.haml
#search.col-1-2
  %h1 Search for providers
  = form_tag search_users_path, method: "GET", remote: :true do
    %fieldset#distance
      = label_tag :distance, "by distance in miles"
      = select_tag :distance, options_for_select(['3', '5', '10'])
      = submit_tag :search

  #map-canvas{ data: { charity: @charity_as_json.to_json, providers: @providers_as_json.to_json } }
  = javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyAHUYHURP4c_vUvTGCT-AkrFNlu-KdUBvg&callback=initMap", :async => true, :defer => true

#providers.col-1-2
  %h2 List of providers that have donated contributions
  %ul#results
    %h2 Organization Name
    - @providers.each do |provider|
      = render provider

app/views/providers/search.js.erb
$("h1#providers").text("List of providers within <%= @distance %> miles distance")
$("#results").html("<span><a href='<% users_path %>'> See all providers</a></span><% @providers.each do |provider| %><%= j render provider %><% end %>");
var providers = ("<%= @providers_as_json.to_json %>").replace(/&quot;/g,'"');

$("#map-canvas").data("providers",JSON.parse(providers));
initMap();

app/views/user_notification/notification.html.erb
<h1>Provider notification</h1>
<p>
  Dear provider <%= @provider.email %>
  The following charity will come to collect your contribution <%= @charity %>
</p>